# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mojovation Consulting
email: neil@mojovation.co.uk
author: Neil Studd
description: Helping you to succeed, grow and flourish within an agile world. 🌍
baseurl: "" # the subpath of your site, e.g. /blog
logo: /assets/img/logo-transparent.png
url: "https://mojovation.co.uk"
contact_cta: >- 
  ✉️ To learn more about how Mojovation Consulting can help you and your team to flourish, 
  read about <a href="/services">our service packages</a> or complete <a href="/contact">our contact form</a>.
twitter_username: neilstudd
github_username:  neilstudd

# Pagination settings
paginate: 20 # Number of posts per page
paginate_path: "/blog/page:num/"

feed:
  posts_limit: 20

jekyll_get_json:
  - data: ecologi
    json: 'https://public.ecologi.com/users/neilstudd/impact'
  - data: peloton
    json: 'https://www.neilstudd.com/pelosummary.php'

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-get-json

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
