name: Daily Deploy

on:
  schedule:
    - cron:  '10 18 * * *' # Runs every day at 6:10pm UTC

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # A personal token with repo access
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
